# Generated by Django 6.0.6 on 2026-10-01 16:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="What customers type, e.g. FALL20. Capitalization doesn't matter.", max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'Use only letters, numbers, and hyphens.')])),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent off'), ('AMOUNT', 'Dollars off')], default='PERCENT', max_length=7, verbose_name='discount type')),
                ('value', models.DecimalField(decimal_places=2, help_text='A percentage (1–100) or a dollar amount, depending on the type.', max_digits=10, verbose_name='discount')),
                ('scope', models.CharField(choices=[('ORDER', 'The whole order'), ('PRODUCTS', 'Selected products only')], default='ORDER', max_length=8, verbose_name='applies to')),
                ('starts_on', models.DateField(verbose_name='first day')),
                ('ends_on', models.DateField(verbose_name='last day')),
                ('is_retired', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='products.product')),
            ],
            options={
                'ordering': ['-starts_on', 'code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.coupon'),
        ),
    ]
