# Generated by Django 6.0.6 on 2026-10-09 20:22

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='JPEG, PNG, or WebP image, up to 5 MB.', max_length=255, upload_to=products.models.product_image_path),
        ),
    ]
